// apps/panel/src/routes/cuotas/registrar/+page.svelte
<script lang="ts">
	import { TipoDeCuota } from '$lib/schemas';
	import {
		Button,
		Checkbox,
		Datepicker,
		Helper,
		Input,
		Label,
		Radio,
		Select,
		Table,
		TableBody,
		TableBodyCell,
		TableBodyRow,
		TableHead,
		TableHeadCell
	} from 'flowbite-svelte';
	import { CheckOutline, FileLinesOutline, PlusOutline } from 'flowbite-svelte-icons';
	import { superForm } from 'sveltekit-superforms';
	import type { PageProps } from './$types';
	import AgregarGastoModal from './components/AgregarGastoModal.svelte';


  let { data }: PageProps = $props();

  const { form } = superForm(data.form, {dataType: 'json'});

  let agregar_gasto_modal: ReturnType<typeof AgregarGastoModal>;
</script>

<h1>Crear Nueva Cuota</h1>
<p class="text-gray-500">Complete el formulario para crear una nueva cuota en el sistema</p>
<pre>{JSON.stringify($form, null, 2)}</pre>
<form action="">
 <section>
  <h3>Tipo de Cuota</h3>
  <div class="grid gap-5">
    <div class="radio">a
      <Radio name="tipo" value="REGULAR" bind:group={$form.tipo}>Mensualidad Regular</Radio>
      <Helper class="radio__helper">
        Some helper text here
      </Helper>
    </div>
    <div class="radio">
      <Radio name="tipo" value="ESPECIAL" bind:group={$form.tipo}>Cuota Especial</Radio>
      <Helper class="radio__helper">
        Some helper text here
      </Helper>
    </div>
  </div>
 </section>   
  {#if $form.tipo === TipoDeCuota.Regular}

  <section class="grid gap-5">
  <h3>Periodo</h3>
  <div class="grid grid-cols-2 gap-x-5 gap-y-3">
    <div>
      <Label for="anio">Año</Label>
      <Select id="anio" placeholder="Seleccione el año" disabled={$form.periodo.actual}>
        <option value="2024">2024</option>
        <option value="2025">2025</option>
        <option value="2026">2026</option>
        <option value="2027">2027</option>

      </Select>
    </div>
    <div>
      <Label for="mes">Mes</Label>
      <Select id="mes" placeholder="Seleccione el mes" bind:value={$form.periodo.mes} disabled={$form.periodo.actual}>
        <option value="1">Enero</option>
        <option value="2">Febrero</option>
        <option value="3">Marzo</option>
        <option value="4">Abril</option>
        <option value="5">Mayo</option>
        <option value="6">Junio</option>
        <option value="7">Julio</option>
        <option value="8">Agosto</option>
        <option value="9">Septiembre</option>
        <option value="10">Octubre</option>
        <option value="11">Noviembre</option>
        <option value="12">Diciembre</option>
      </Select>
    </div>

    <div>
      <Checkbox id="useCurrentYear" bind:checked={$form.periodo.actual}>Usar año actual</Checkbox>
    </div>
  </div>
  <div class="grid grid-cols-2 gap-x-5 gap-y-3">
    <div>
      <Label for="fecha_emision">Fecha de Emisión</Label>
      <Datepicker id="fecha_emision" placeholder="dd/mm/aaaa" bind:value={$form.periodo.fecha_emision} />
    </div>
    <div>
      <Label for="fecha_limite">Fecha Límite de Pago</Label>
      <Datepicker id="fecha_limite" placeholder="dd/mm/aaaa" bind:value={$form.periodo.fecha_limite} />
    </div>
  </div>
 </section>  
 <section>
   <div class="flex justify-between items-center">
     <h3>Desglose de Gastos</h3>
     <Button color="alternative" onclick={() => agregar_gasto_modal?.show()}><PlusOutline /> Agregar Gasto</Button>
   </div>
   <Table>
    <TableHead>
      <TableHeadCell>ID</TableHeadCell>
      <TableHeadCell>Concepto</TableHeadCell>
      <TableHeadCell>Monto</TableHeadCell>
      <TableHeadCell>Fecha</TableHeadCell>
      <TableHeadCell>Proveedor</TableHeadCell>
    </TableHead>
    <TableBody>
      <TableBodyRow>
        <TableBodyCell>bogy5a</TableBodyCell>
        <TableBodyCell>Pago de globos</TableBodyCell>
        <TableBodyCell>$ 1,34</TableBodyCell>
        <TableBodyCell>14/12/2025</TableBodyCell>
        <TableBodyCell>Gas Natural</TableBodyCell>
      </TableBodyRow>
   
    </TableBody>
   </Table>
 </section>
 <section>
  <h3>Adjuntar Documentos (opcional)</h3>
  <div class="bg-gray-100 min-h-48 rounded-xl border border-gray-300 border-dashed" style="">
    
  </div>
 </section>
{:else if $form.tipo === TipoDeCuota.Especial}
<section>
  <Label for="descripcion">Descripción</Label>
  <Input type="text" id="descripcion" placeholder="Ej. Reparación de Bomba de Agua" required />
</section>
  {/if}

 <div class="flex justify-end gap-3">
  <Button color="alternative">Cancelar</Button>
  <Button color="alternative"><FileLinesOutline />Guardar Borrador</Button>
  <Button><CheckOutline /> Publicar Cuota</Button>
 </div>
</form>

<AgregarGastoModal bind:this={agregar_gasto_modal}/>

// apps/panel/src/app/cuotas/registrar/page.tsx
"use client";

import { Checkbox } from "@/components/ui/checkbox";
import { DatePickerInput } from "@/components/ui/date-picker-input";
import {
  Field,
  FieldContent,
  FieldDescription,
  FieldLabel,
} from "@/components/ui/field";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { MoreHorizontalIcon, Plus } from "lucide-react";

export default function RegistrarCuota() {
  return (
    <>
      <h1>Crear Nueva Cuota</h1>
      <p className="text-gray-500">
        Complete el formulario para crear una nueva cuota en el sistema.
      </p>
      <form>
        <section>
          <h3>Tipo de cuota</h3>
          <RadioGroup defaultValue="regular" className="w-fit">
            <Field orientation="horizontal">
              <RadioGroupItem value="regular" id="regular" />
              <FieldContent>
                <FieldLabel htmlFor="regular">Mensualidad Regular</FieldLabel>
                <FieldDescription>Cuota mensual estándar</FieldDescription>
              </FieldContent>
            </Field>
            <Field orientation="horizontal">
              <RadioGroupItem value="especial" id="especial" />
              <FieldContent>
                <FieldLabel htmlFor="especial">Cuota Especial</FieldLabel>
                <FieldDescription>
                  Cuota destinada a algún tipo de inprevisto
                </FieldDescription>
              </FieldContent>
            </Field>
          </RadioGroup>
        </section>
        <section>
          <h3>Periodo</h3>
          {/* Año */}
          <div className="flex gap-5">
            <Field className="">
              <FieldLabel>Año</FieldLabel>
              <Select>
                <SelectTrigger>
                  <SelectValue placeholder="Seleccione el año" />
                </SelectTrigger>
                <SelectContent>
                  <SelectGroup>
                    <SelectItem value="2023">2023</SelectItem>
                    <SelectItem value="2024">2024</SelectItem>
                    <SelectItem value="2025">2025</SelectItem>
                  </SelectGroup>
                </SelectContent>
              </Select>
            </Field>
            {/* Mes */}
            <Field className="">
              <FieldLabel>Mes</FieldLabel>
              <Select>
                <SelectTrigger>
                  <SelectValue placeholder="Seleccione el mes" />
                </SelectTrigger>
                <SelectContent>
                  <SelectGroup>
                    <SelectItem value="1">Enero</SelectItem>
                    <SelectItem value="2">Febrero</SelectItem>
                    <SelectItem value="3">Marzo</SelectItem>
                    <SelectItem value="4">Abril</SelectItem>
                    <SelectItem value="5">Mayo</SelectItem>
                    <SelectItem value="6">Junio</SelectItem>
                    <SelectItem value="7">Julio</SelectItem>
                    <SelectItem value="8">Agosto</SelectItem>
                    <SelectItem value="9">Septiembre</SelectItem>
                    <SelectItem value="10">Octubre</SelectItem>
                    <SelectItem value="11">Noviembre</SelectItem>
                    <SelectItem value="12">Diciembre</SelectItem>
                  </SelectGroup>
                </SelectContent>
              </Select>
            </Field>
          </div>
          <Field orientation="horizontal">
            <Checkbox id="anio_actual" name="anio_actual" />
            <FieldLabel htmlFor="anio_actual">Usar año actual</FieldLabel>
          </Field>

          <div className="flex gap-5">
            {/* TODO: mejorar el input con su mask y mejor seleccion */}
            <Field className="">
              <FieldLabel htmlFor="fecha_emision">Fecha de emisión</FieldLabel>
              <DatePickerInput
                placeholder="dd/mm/aaaa"
                locale="es-VE"
                id="fecha_emision"
              />
            </Field>
            {/* TODO: mejorar el input con su mask y mejor seleccion */}
            <Field className="">
              <FieldLabel htmlFor="fecha_limite">
                Fecha limite de pago
              </FieldLabel>
              <DatePickerInput
                placeholder="dd/mm/aaaa"
                locale="es-VE"
                id="fecha_limite"
              />
            </Field>
          </div>
        </section>

        <section>
          <div className="flex justify-between items-center">
            <h3>Desglose de gastos</h3>
            <Button variant="outline">
              <Plus />
              Agregar Gasto
            </Button>
          </div>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="font-semibold uppercase">ID</TableHead>
                <TableHead className="font-semibold uppercase">
                  Concepto
                </TableHead>
                <TableHead className="font-semibold uppercase">Monto</TableHead>
                <TableHead className="font-semibold uppercase">Fecha</TableHead>
                <TableHead className="font-semibold uppercase">
                  Proveedor
                </TableHead>
                <TableHead className="text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow>
                <TableCell className="font-medium">bogy5a</TableCell>
                <TableCell>$29.99</TableCell>
                <TableCell className="text-right">
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <Button variant="ghost" size="icon" className="size-8">
                        <MoreHorizontalIcon />
                        <span className="sr-only">Open menu</span>
                      </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align="end">
                      <DropdownMenuItem>Edit</DropdownMenuItem>
                      <DropdownMenuItem>Duplicate</DropdownMenuItem>
                      <DropdownMenuSeparator />
                      <DropdownMenuItem variant="destructive">
                        Delete
                      </DropdownMenuItem>
                    </DropdownMenuContent>
                  </DropdownMenu>
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell className="font-medium">
                  Mechanical Keyboard
                </TableCell>
                <TableCell>$129.99</TableCell>
                <TableCell className="text-right">
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <Button variant="ghost" size="icon" className="size-8">
                        <MoreHorizontalIcon />
                        <span className="sr-only">Open menu</span>
                      </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align="end">
                      <DropdownMenuItem>Edit</DropdownMenuItem>
                      <DropdownMenuItem>Duplicate</DropdownMenuItem>
                      <DropdownMenuSeparator />
                      <DropdownMenuItem variant="destructive">
                        Delete
                      </DropdownMenuItem>
                    </DropdownMenuContent>
                  </DropdownMenu>
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell className="font-medium">USB-C Hub</TableCell>
                <TableCell>$49.99</TableCell>
                <TableCell className="text-right">
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <Button variant="ghost" size="icon" className="size-8">
                        <MoreHorizontalIcon />
                        <span className="sr-only">Open menu</span>
                      </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align="end">
                      <DropdownMenuItem>Edit</DropdownMenuItem>
                      <DropdownMenuItem>Duplicate</DropdownMenuItem>
                      <DropdownMenuSeparator />
                      <DropdownMenuItem variant="destructive">
                        Delete
                      </DropdownMenuItem>
                    </DropdownMenuContent>
                  </DropdownMenu>
                </TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </section>
      </form>
    </>
  );
}
